# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDataset1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BDoriginale', models.CharField(max_length=100)),
                ('Champ', models.CharField(max_length=100)),
                ('AWDR', models.FloatField(null=True)),
                ('PrevContribN', models.IntegerField(null=True)),
                ('TillPractice', models.CharField(max_length=100)),
                ('TillType', models.CharField(max_length=100)),
                ('PrevCrop', models.CharField(max_length=100)),
                ('PrevContribN_cls', models.CharField(max_length=50)),
                ('SoilType', models.CharField(max_length=50)),
                ('SoilTexture_cls', models.CharField(max_length=50)),
                ('Yld0', models.FloatField(null=True)),
                ('Yld50', models.FloatField(null=True)),
                ('Yld100', models.FloatField(null=True)),
                ('Yld150', models.FloatField(null=True)),
                ('Yld200', models.FloatField(null=True)),
                ('Ymodel0', models.FloatField(null=True)),
                ('Ymax', models.FloatField(null=True)),
                ('Nymax', models.FloatField(null=True)),
                ('a', models.FloatField(null=True)),
                ('b', models.FloatField(null=True)),
                ('c', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'PaasDataset1',
            },
        ),
    ]
