# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0002_userrquestsite_usertransaction'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userrquestsite',
            table='dssservice_userrquestsite',
        ),
        migrations.AlterModelTable(
            name='usertransaction',
            table='dssservice_usertransaction',
        ),
    ]
