# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0003_auto_20170413_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='dsslookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=100, null=True)),
                ('key', models.CharField(max_length=100, null=True)),
                ('value', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'dssservice_dsslookup',
            },
        ),
        migrations.CreateModel(
            name='PlotYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(null=True)),
                ('Longitude', models.FloatField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('SoilType', models.CharField(max_length=100)),
                ('ClayRatio', models.FloatField(null=True)),
                ('SOM', models.FloatField(null=True)),
                ('TillType', models.CharField(max_length=100, null=True)),
                ('TillType_int', models.IntegerField(null=True)),
                ('PrevCrop', models.CharField(max_length=100, null=True)),
                ('PrevContribN_int', models.IntegerField(null=True)),
                ('CHU', models.IntegerField(null=True)),
                ('PPT', models.IntegerField(null=True)),
                ('AWDR', models.FloatField(null=True)),
                ('Nrate', models.IntegerField()),
                ('Yield', models.FloatField()),
                ('Source', models.CharField(max_length=150)),
                ('Verified', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'dssservice_plotyield',
            },
        ),
        migrations.CreateModel(
            name='SiteField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_Field_Name', models.CharField(max_length=200, null=True)),
                ('Data_Soruce', models.CharField(max_length=100, null=True)),
                ('Province', models.CharField(max_length=100, null=True)),
                ('Region', models.CharField(max_length=200, null=True)),
                ('Town', models.CharField(max_length=100, null=True)),
                ('Site', models.CharField(max_length=100, null=True)),
                ('Field_Number', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'dssservice_sitefield',
            },
        ),
        migrations.AddField(
            model_name='pdataset1',
            name='TillType_int',
            field=models.IntegerField(choices=[(0, 'No till'), (1, 'Conventional')], null=True),
        ),
        migrations.AddField(
            model_name='userrquestsite',
            name='CHU',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pdataset1',
            name='PrevContribN_cls',
            field=models.CharField(choices=[('Weak', '0 - 25 kg/ha'), ('Medium', '25 - 50 kg/ha'), ('Strong', '50 -100 kg/ha')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plotyield',
            name='SiteFieldId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='passapp.SiteField'),
        ),
    ]
