# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0004_auto_20171005_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrquestsite',
            name='climate',
        ),
        migrations.AddField(
            model_name='userrquestsite',
            name='SOM',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userrquestsite',
            name='awdr',
            field=models.FloatField(null=True),
        ),
    ]
